Raised version to 3.3.1 and adapted old pyarrow patch
conda-forge/snowflake-connector-python-feedstock pull request #150
Opened 2023-10-30 11:49 UTC by timostrunk

The package offsets were broken. I fixed it and raised version to 3.3.1

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-10-30 11:51 UTC, timostrunk commented
I rewrote the arrow-cpp dependency to libarrow

2023-10-30 11:51 UTC, timostrunk commented
@conda-forge-admin, please rerender

2023-10-30 17:01 UTC, xhochy requested changes

2023-10-30 17:01 UTC, xhochy commented on recipe/0001-drop-pyarrow-versions-build-with-proper-ABI-settings.patch
> -Date: Mon, 20 Mar 2023 08:36:54 +0100
Please don't drop attribution and git structure on these patches.

2023-10-30 18:06 UTC, timostrunk commented
@conda-forge-admin, please rerender

2023-10-31 08:26 UTC, timostrunk commented
I recreated this PR in #151 and removed unrequired patches. I would favor merging #151 and closing this one.

2023-11-07 14:19 UTC, closed without merging